<a href="https://colab.research.google.com/github/amafanasyeva/DIP_MATLAB/blob/master/00_tensorflow_fundamentals_Afanasyeva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import datetime

print(f"Notebook last run (end-to-end): {datetime.datetime.now()}")

Notebook last run (end-to-end): 2024-01-21 21:58:22.777047


In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # find the version number (should be 2.x+)

2.15.0


In [15]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(5)
scalar, scalar.ndim, scalar.shape, tf.size(scalar)

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 0,
 TensorShape([]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [16]:
my_vector = tf.constant([5, 5])
my_vector, my_vector.ndim, my_vector.shape, tf.size(my_vector)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>,
 1,
 TensorShape([2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [17]:
my_matrix = tf.constant([[5, 9],
                      [9, 5]])
my_matrix, my_matrix.ndim, my_matrix.shape, tf.size(my_matrix)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 9],
        [9, 5]], dtype=int32)>,
 2,
 TensorShape([2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [18]:
my_tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
my_tensor, my_tensor.ndim, my_tensor.shape, tf.size(my_tensor)

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>,
 3,
 TensorShape([3, 2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=18>)

In [35]:
random_tensor_1 = tf.random.Generator.from_seed(42)
random_tensor_1 = random_tensor_1.normal(shape=(5, 300))
random_tensor_2 = tf.random.Generator.from_seed(42)
random_tensor_2 = random_tensor_2.normal(shape=(5, 300))
random_tensor_1, random_tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
          1.216793  , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
         -0.73970354,  0.0177109 ],
        [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
          0.5656089 ,  0.18439196]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
          1.216793  , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 

In [36]:
#tf.matmul(random_tensor_1, random_tensor_2)
random_tensor_1 @ tf.transpose(random_tensor_2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[272.44012  , -17.250706 , -34.88533  , -12.265072 , -22.346771 ],
       [-17.250706 , 335.51385  ,  -3.666809 ,  -1.7807384, -18.89357  ],
       [-34.88533  ,  -3.666809 , 333.2705   ,   4.595558 ,  -9.527701 ],
       [-12.265072 ,  -1.7807384,   4.595558 , 317.00775  ,   4.2550097],
       [-22.346771 , -18.89357  ,  -9.527701 ,   4.2550097, 295.76996  ]],
      dtype=float32)>

In [34]:
tf.transpose(random_tensor_2)

<tf.Tensor: shape=(300, 5), dtype=float32, numpy=
array([[-0.7565803 , -0.88051033, -1.5306779 ,  0.84324265,  0.04888754],
       [-0.06854702, -0.32426047, -0.86202925, -0.23379943, -0.66408694],
       [ 0.07595026, -2.4847078 , -0.16359143,  0.4276398 , -1.787366  ],
       ...,
       [-1.071834  ,  0.16512105,  0.34288085, -1.0428714 ,  0.1947453 ],
       [-1.0722276 ,  1.155565  ,  1.216793  , -0.73970354,  0.5656089 ],
       [-0.00586287, -0.10707551, -1.24293   ,  0.0177109 ,  0.18439196]],
      dtype=float32)>

In [33]:
tf.tensordot(random_tensor_1, tf.transpose(random_tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[272.44012  , -17.250706 , -34.88533  , -12.265072 , -22.346771 ],
       [-17.250706 , 335.51385  ,  -3.666809 ,  -1.7807384, -18.89357  ],
       [-34.88533  ,  -3.666809 , 333.2705   ,   4.595558 ,  -9.527701 ],
       [-12.265072 ,  -1.7807384,   4.595558 , 317.00775  ,   4.2550097],
       [-22.346771 , -18.89357  ,  -9.527701 ,   4.2550097, 295.76996  ]],
      dtype=float32)>

In [38]:
random_tensor_3 = tf.random.Generator.from_seed(42)
random_tensor_3 = random_tensor_3.normal(shape=(224, 224, 3))

In [40]:
tf.reduce_max(random_tensor_3)

<tf.Tensor: shape=(), dtype=float32, numpy=4.4032865>

In [41]:
tf.reduce_min(random_tensor_3)

<tf.Tensor: shape=(), dtype=float32, numpy=-4.848316>

In [42]:
random_tensor_4 = tf.random.Generator.from_seed(42)
random_tensor_4 = random_tensor_4.normal(shape=(1, 224, 224, 3))

In [43]:
random_tensor_4_squeezed = tf.squeeze(random_tensor_4)
random_tensor_4_squeezed.shape, random_tensor_4_squeezed.ndim

(TensorShape([224, 224, 3]), 3)

In [53]:
import numpy as np
random_tensor_5 = tf.constant(np.random.random(10))
random_tensor_5, tf.argmax(random_tensor_5)

(<tf.Tensor: shape=(10,), dtype=float64, numpy=
 array([0.56056822, 0.21647101, 0.85292544, 0.45721517, 0.65043516,
        0.0834565 , 0.86649845, 0.87096848, 0.03041729, 0.95046701])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=9>)